=begin
  @author Jon Ho

  Each new term in the Fibonacci sequence is generated by adding the
  previous two terms. By starting with 1 and 2, the first 10 terms
  will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not
  exceed four million, find the sum of the even-valued terms.
=end

@sum = 0
@FOURMILLION = 4000000
@term = 0

def fib(n)
  n < 2 ? n : fib(n - 1) + fib(n - 2)
end

while (fib(@term) < @FOURMILLION) do
  if(fib(@term) % 2 == 0)
    @sum += fib(@term)
  end
  
  @term += 1
end

puts @sum
