/*
 * Even Fibonacci numbers
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

#define FOURMILLION 4000000

/*
 * Return the nth Fibonacci number.
 */
int fib(int n)
{
  return n < 2 ? n : fib(n - 1) + fib(n - 2);
}

/*
 * Sum even Fibonacci numbers up to four million.
 */
void evenFibber()
{
  int i = 0;
  int sum = 0;
  int fibNum = 0;
  while((fibNum = fib(i)) < FOURMILLION)
  {
  	if(fibNum % 2 == 0)
      sum += fibNum;

    i++;
  }

  printf("Even Fibonacci numbers summed up to four million is: %d\n", sum);
}

int main(void)
{
  evenFibber();
  return 0;
}