/*
 * Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */

public class p002 {
	private static final int FOUR_MILLION = 4000000;

	public static int fib(int n) {
		return n < 2 ? n : fib(n - 1) + fib(n - 2);
	}

	public static void fibber() {
		int n = 0;
		int sum = 0;
		int myFib = fib(n);

		while(myFib < FOUR_MILLION) {
			if(myFib % 2 == 0)
				sum += myFib;

			myFib = fib(++n);
		}

		System.out.print("The sum of the Fibonacci sequences whose values");
		System.out.println(" are even and below four million is: " + sum);
	}

	public static void main(String[] args) {
		fibber();
	}
}
