"""
  Each new term in the Fibonacci sequence is generated by adding the
  previous two terms. By starting with 1 and 2, the first 10 terms
  will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not
  exceed four million, find the sum of the even-valued terms.
"""

sums = 0
FM = 4000000
term = 0

def fib(n):
	# ternary op in python was added in 2.5
	# below is the ternary op equivalent but it's not popular to use
	return n if n < 2 else fib(n - 1) + fib(n - 2)

while fib(term) < FM:
	if fib(term) % 2 == 0:
		sums += fib(term)

	term += 1

print sums